# Generated by Django 3.0.3 on 2020-02-19 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dancingcubeapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='map',
            name='difficulty',
            field=models.CharField(choices=[('1', 'easy'), ('2', 'medium'), ('3', 'hard')], default='1', max_length=1),
        ),
        migrations.AddField(
            model_name='map',
            name='map',
            field=models.FileField(default='rien.txt', upload_to='media/maps/'),
        ),
        migrations.AddField(
            model_name='map',
            name='music',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='map',
            name='uploader',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='map',
            name='name',
            field=models.CharField(default='', max_length=30),
        ),
    ]
