# Generated by Django 3.0.3 on 2020-02-26 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dancingcubeapp', '0002_auto_20200219_1712'),
    ]

    operations = [
        migrations.AddField(
            model_name='map',
            name='image',
            field=models.ImageField(blank=True, upload_to='media/images/'),
        ),
        migrations.AlterField(
            model_name='map',
            name='map',
            field=models.FileField(blank=True, upload_to='media/maps/'),
        ),
        migrations.AlterField(
            model_name='map',
            name='music',
            field=models.FileField(blank=True, upload_to='media/musics/'),
        ),
    ]
