# Generated by Django 3.0.3 on 2020-02-27 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dancingcubeapp', '0003_auto_20200226_1659'),
    ]

    operations = [
        migrations.AlterField(
            model_name='map',
            name='image',
            field=models.ImageField(upload_to='media/images/'),
        ),
        migrations.AlterField(
            model_name='map',
            name='map',
            field=models.FileField(upload_to='media/maps/'),
        ),
        migrations.AlterField(
            model_name='map',
            name='music',
            field=models.FileField(upload_to='media/musics/'),
        ),
    ]
