# Generated by Django 3.0.3 on 2020-04-02 12:49

import dancingcubeapp.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dancingcubeapp', '0005_auto_20200402_1408'),
    ]

    operations = [
        migrations.AlterField(
            model_name='map',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='media/musics/', validators=[dancingcubeapp.validators.validate_file_extension_for_image]),
        ),
        migrations.AlterField(
            model_name='map',
            name='map',
            field=models.FileField(upload_to='media/maps/', validators=[dancingcubeapp.validators.validate_file_extension_for_map]),
        ),
        migrations.AlterField(
            model_name='map',
            name='music',
            field=models.FileField(upload_to='media/musics/', validators=[dancingcubeapp.validators.validate_file_extension_for_music]),
        ),
    ]
