# Generated by Django 3.0.3 on 2020-04-07 22:57

import dancingcubeapp.validators
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dancingcubeapp', '0007_auto_20200402_1520'),
    ]

    operations = [
        migrations.AddField(
            model_name='map',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='likes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='map',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='media\\images\\', validators=[dancingcubeapp.validators.validate_file_extension_for_image]),
        ),
        migrations.AlterField(
            model_name='map',
            name='map',
            field=models.FileField(upload_to='media\\maps\\', validators=[dancingcubeapp.validators.validate_file_extension_for_map]),
        ),
        migrations.AlterField(
            model_name='map',
            name='music',
            field=models.FileField(upload_to='media\\musics\\', validators=[dancingcubeapp.validators.validate_file_extension_for_music]),
        ),
    ]
