# Generated by Django 3.0.3 on 2020-04-27 06:47

import dancingcubeapp.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dancingcubeapp', '0009_auto_20200416_0312'),
    ]

    operations = [
        migrations.CreateModel(
            name='MapFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='media\\maps\\', validators=[dancingcubeapp.validators.validate_file_extension_for_map])),
                ('parentMap', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dancingcubeapp.Map')),
            ],
        ),
    ]
